# Generated by Django 2.1.4 on 2018-12-22 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TEACHER_NAME', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TIMESTAMP', models.DateTimeField(auto_now_add=True)),
                ('STUDENT_NAME', models.CharField(max_length=200)),
                ('COLLEGE_NAME', models.CharField(max_length=200)),
                ('PREVIOUS_CLASS_MARKS', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='PREVIOUS MARKS (IN PERCENTAGE)')),
                ('MEDIUM', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi')], max_length=200)),
                ('PREFERED_WAY_OF', models.CharField(choices=[('Theoritical', 'Theoritical'), ('Practical', 'Practical'), ('Numerical', 'Numerical')], max_length=200, verbose_name='PREFERED SUBJECT TYPE')),
                ('STUDY_HOURS_DAILY', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)], verbose_name='Study Hours Daily')),
                ('TEACHERS_YOU_DISLIKED', models.ManyToManyField(related_name='DISLIKED', to='tutor.Teacher')),
                ('TEACHERS_YOU_LIKED', models.ManyToManyField(related_name='LIKED', to='tutor.Teacher')),
            ],
        ),
    ]
